/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eu.malycha.hazelcast.eventsourcing.server;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class HazelcastServer {

    public static void main(String[] args) {
        SpringApplication.run(HazelcastServer.class, args);
    }
}
